FROM nvcr.io/nvidia/merlin/merlin-tensorflow:23.12

RUN pip install --no-cache-dir feast==0.31 faiss-gpu redis

RUN curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip \
 && unzip awscliv2.zip && ./aws/install \
 && rm -rf aws awscliv2.zip