name: "nvt_item_transform"
backend: "python"
input {
  name: "item_id"
  data_type: TYPE_INT32
  dims: [ -1 ]
}
input {
  name: "price"
  data_type: TYPE_FP32
  dims: [ -1 ]
}
input {
  name: "category_l1"
  data_type: TYPE_INT32
  dims: [ -1 ]
}
input {
  name: "category_l2"
  data_type: TYPE_INT32
  dims: [ -1 ]
}
input {
  name: "item_gender"
  data_type: TYPE_INT32
  dims: [ -1 ]
}
output {
  name: "item_id"
  data_type: TYPE_INT32
  dims: [ -1 ]
}
output {
  name: "category_l1"
  data_type: TYPE_INT32
  dims: [ -1 ]
}
output {
  name: "category_l2"
  data_type: TYPE_INT32
  dims: [ -1 ]
}
output {
  name: "item_gender"
  data_type: TYPE_INT32
  dims: [ -1 ]
}
output {
  name: "price_log_norm"
  data_type: TYPE_FP32
  dims: [ -1 ]
}
